  # This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    branches:
      - "main"
    tags:
      - v**
  workflow_dispatch:


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v3
        with:
          name: policies
          path: | 
            *.pdf
          retention-days: 180
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.pdf
          tag_name: ${{github.ref_name}}
