  # This is a basic workflow to help you get started with Actions

name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    paths:
      - ./**.tex

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: Pull
        run: git pull

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **.tex
        
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      - id: debug
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ${{ steps.changed-files.outputs.all_changed_files }}
          glob_root_file: true
          latexmk_use_xelatex: true

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.pdf -f
          git commit -m "📙 Update documents pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'documents_dev'
          force: true
